import { useState } from 'react';
import { Link } from 'react-router';
import data from '../../../../recursos-compartidos/demo/gestion.json';
import { Avatar, Badge, Glyph, Modal } from './ui';

export function Changes({ notify, onApply }: { notify: (message: string) => void; onApply: () => void }) {
  const [tab, setTab] = useState('Pendientes de aplicar');
  const [checked, setChecked] = useState(false);
  const [applied, setApplied] = useState(false);
  const [modal, setModal] = useState(false);
  const [reviewed, setReviewed] = useState(false);
  return <>
    <div className="crm-page-heading"><div><div className="crm-title-line"><h1>Control de cambios</h1><Badge tone="blue">1 actualización</Badge></div><p>Actualiza los procesos con control sobre cada expediente.</p></div><Link className="crm-btn" to="/gestion/rutas/residencia-demo"><Glyph name="route" />Abrir configurador</Link></div>
    <div className="crm-metrics crm-metrics--three"><div><span>Versiones pendientes<Glyph name="history" /></span><strong>{applied ? '0' : '1'}<small>Residencia inicial</small></strong></div><div><span>Expedientes evaluados<Glyph name="cases" /></span><strong>2<small>Progreso preservado</small></strong></div><div><span>Revisión individual<Glyph name="eye" /></span><strong>1<small>Requiere una decisión jurídica</small></strong></div></div>
    <div className="crm-tabs" role="tablist" aria-label="Control de cambios">{['Pendientes de aplicar', 'Registro de actividad'].map(t => <button key={t} role="tab" aria-selected={tab === t} onClick={() => setTab(t)}>{t}{t === 'Pendientes de aplicar' && <span>{applied ? 0 : 1}</span>}</button>)}</div>
    {tab === 'Pendientes de aplicar' ? <>
      <div className="crm-change-layout" data-capture="board"><section className="crm-card crm-change-main"><div className="crm-card-title"><div><span className="crm-overline">RESIDENCIA INICIAL · V1 → V2</span><h2>Instrucciones documentales más claras</h2></div><Badge tone={applied ? 'green' : 'amber'}>{applied ? 'Aplicada' : 'Pendiente de aplicar'}</Badge></div><p className="crm-change-intro">Solicitar todas las páginas en orden y comprobar que las fechas sean legibles antes del envío.</p><div className="crm-diff-grid"><div><span className="crm-diff-label">− VERSIÓN 1 · ACTUAL</span><p>{data.ruta.pasos[1].instruccion}</p></div><div><span className="crm-diff-label">+ VERSIÓN 2 · PROPUESTA</span><p>Adjunta una copia completa, <mark>con todas las páginas en orden. Revisa que las fechas se lean</mark> antes de enviarla.</p></div></div><div className="crm-change-scope"><Glyph name="file" /><span><strong>Un cambio de contenido</strong><small>Preparar documentación · se conservan pasos, documentos y tareas completadas.</small></span></div></section>
      <aside className="crm-card crm-change-summary"><h2>Detalle de la versión</h2><dl><div><dt>Responsable</dt><dd><Avatar name="Marta Pérez" />Marta Pérez</dd></div><div><dt>Revisión jurídica</dt><dd><Badge tone="green">Revisada · ejemplo</Badge></dd></div><div><dt>Vigencia propuesta</dt><dd><Glyph name="calendar" size={16} />01 oct. 2026</dd></div><div><dt>Alcance</dt><dd>Instrucciones al cliente</dd></div></dl><div className="crm-info"><Glyph name="lock" size={17} /><span>Los cambios se aplican solo a los expedientes seleccionados.</span></div></aside></div>
      <section className="crm-card crm-impact"><div className="crm-card-title"><div><h2>Impacto en los expedientes</h2><p>Revisa el estado de cada caso antes de actualizar su versión.</p></div><Badge>2 expedientes</Badge></div><div className="crm-table-wrap"><table className="crm-table"><thead><tr><th><span className="crm-sr-only">Seleccionar</span></th><th>Cliente / expediente</th><th>Paso actual</th><th>Versión</th><th>Evaluación de impacto</th><th /></tr></thead><tbody><tr><td><input aria-label="Seleccionar expediente de Lucía" type="checkbox" checked={checked || applied} disabled={applied} onChange={e => setChecked(e.target.checked)} /></td><td><div className="crm-person"><Avatar name="Lucía Martínez" /><span><strong>Lucía Martínez</strong><small>AS-0142 · 1 paso completado</small></span></div></td><td>Preparar documentación</td><td><Badge>v{applied ? '2' : '1'}</Badge></td><td><Badge tone="green">{applied ? 'Actualización aplicada' : 'Compatible'}</Badge><small className="crm-cell-note">El paso todavía no está completado</small></td><td><Link className="crm-icon-button" aria-label="Ver expediente de Lucía" to="/gestion/expedientes/lucia-demo"><Glyph name="arrow" size={17} /></Link></td></tr><tr><td><input type="checkbox" disabled aria-label="Omar requiere revisión individual" /></td><td><div className="crm-person"><Avatar name="Omar Benali" color={1} /><span><strong>Omar Benali</strong><small>AS-0187 · 3 pasos completados</small></span></div></td><td>Revisión completada</td><td><Badge>v1</Badge></td><td><Badge tone="amber">Revisión individual</Badge><small className="crm-cell-note">La documentación ya se ha validado</small></td><td><Link className="crm-icon-button" aria-label="Ver expediente de Omar" to="/gestion/expedientes/omar-demo"><Glyph name="arrow" size={17} /></Link></td></tr></tbody></table></div><div className="crm-table-footer"><span>{applied ? '1 expediente actualizado · 1 conserva su versión' : `${checked ? 1 : 0} de 2 expedientes seleccionados`}</span><button className="crm-btn crm-btn--primary" disabled={!checked || applied} onClick={() => setModal(true)}><Glyph name="check" size={17} />{applied ? 'Cambio aplicado' : 'Revisar y aplicar'}</button></div></section><p className="crm-footnote"><Glyph name="history" size={15} />Cada actualización queda registrada con su responsable, alcance y versión. Cambio de procedimiento ficticio.</p>
    </> : <section className="crm-card"><div className="crm-card-title"><h2>Trazabilidad de los cambios</h2><Badge>Historial de ejemplo</Badge></div><div className="crm-audit">{[...(applied ? [['Cambio aplicado a AS-0142', 'Marta Pérez · Ahora', 'Versión 1 → 2. Entrevista completada conservada. AS-0187 sin cambios.']] : []), ['Revisión de la versión 2 completada', 'Carlos Vidal · Hoy, 10:15', 'Instrucciones revisadas. Pendiente decidir el alcance sobre los casos abiertos.'], ['Borrador de la versión 2 creado', 'Marta Pérez · Hoy, 09:42', 'Actualización de las instrucciones del paso Preparar documentación.'], ['Versión 1 publicada', 'Carlos Vidal · 02 sep., 12:00', 'Ruta inicial disponible para nuevas asignaciones.']].map(([title, who, text]) => <article key={title}><i /><div><h3>{title}</h3><small>{who}</small><p>{text}</p></div></article>)}</div></section>}
    {modal && <Modal title="Aplicar la versión 2 a Lucía" close={() => setModal(false)}><div className="crm-info"><Glyph name="cases" /><span>AS-0142 · Lucía Martínez<br />Se actualizan las instrucciones del paso documental.</span></div><p>Se conservarán la entrevista completada y los documentos recibidos. El expediente de Omar seguirá en la versión 1.</p><label className="crm-checkbox"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} />He revisado el alcance de este cambio de ejemplo.</label><div className="crm-modal-actions"><button className="crm-btn" onClick={() => setModal(false)}>Cancelar</button><button className="crm-btn crm-btn--primary" disabled={!reviewed} onClick={() => { setApplied(true); onApply(); setModal(false); notify('Actualización simulada aplicada a Lucía. Historial registrado.'); }}>Aplicar a 1 expediente</button></div></Modal>}
  </>;
}
