import { useEffect, useState } from 'react';
import { Link, NavLink, useLocation, useNavigate } from 'react-router';
import logo from '../../../../recursos-compartidos/assets/marca/logo-azul-web.jpg';
import { Avatar, Badge, Glyph, Modal, type GlyphName } from './ui';
import { initialCases, initialDocuments, initialTasks, routeNames, type Case } from './model';
import { RouteEditor } from './RouteEditor';
import { Changes } from './Changes';
import './crm.css';

const nav: { path: string; label: string; icon: GlyphName; count?: string; group?: string }[] = [
  { path: '/gestion', label: 'Vista general', icon: 'grid', group: 'DESPACHO' },
  { path: '/gestion/expedientes', label: 'Expedientes', icon: 'cases' },
  { path: '/gestion/tareas', label: 'Tareas y agenda', icon: 'tasks', count: '4' },
  { path: '/gestion/documentos', label: 'Documentos', icon: 'file' },
  { path: '/gestion/mensajes', label: 'Conversaciones', icon: 'chat', count: '2' },
  { path: '/gestion/rutas', label: 'Rutas de trabajo', icon: 'route', group: 'OPERACIÓN' },
  { path: '/gestion/cambios', label: 'Control de cambios', icon: 'history', count: '1' },
  { path: '/gestion/equipo', label: 'Equipo', icon: 'team' },
];
const normalizeSearch = (value: string) => value.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase();
const pathFor = (file: Case) => `/gestion/expedientes/${file.id === 'AS-0142' ? 'lucia-demo' : file.id === 'AS-0187' ? 'omar-demo' : file.id.toLowerCase()}`;
function PageHeading({ title, text, action }: { title: string; text: string; action?: React.ReactNode }) { return <div className="crm-page-heading"><div><h1>{title}</h1><p>{text}</p></div>{action}</div>; }

export function Crm() {
  const [generation, setGeneration] = useState(0);
  return <CrmSession key={generation} reset={() => setGeneration(v => v + 1)} />;
}
function CrmSession({ reset }: { reset: () => void }) {
  const { pathname } = useLocation();
  const navigate = useNavigate();
  const [mobileMenu, setMobileMenu] = useState(false);
  const [compact, setCompact] = useState(() => window.matchMedia('(max-width: 760px)').matches);
  useEffect(() => {
    const media = window.matchMedia('(max-width: 760px)');
    const update = () => setCompact(media.matches);
    media.addEventListener('change', update);
    return () => media.removeEventListener('change', update);
  }, []);
  useEffect(() => {
    if (!mobileMenu) return;
    function closeMenu(event: KeyboardEvent) { if (event.key === 'Escape') { setMobileMenu(false); document.querySelector<HTMLButtonElement>('.crm-menu-toggle')?.focus(); } }
    document.addEventListener('keydown', closeMenu);
    return () => document.removeEventListener('keydown', closeMenu);
  }, [mobileMenu]);
  const [search, setSearch] = useState('');
  const [notification, setNotification] = useState(false);
  const [changeApplied, setChangeApplied] = useState(false);
  const [toast, setToast] = useState('');
  const [cases, setCases] = useState<Case[]>(initialCases);
  const [tasks, setTasks] = useState(initialTasks);
  const [documents, setDocuments] = useState(initialDocuments);
  const [filter, setFilter] = useState('Todos');
  const [caseSearch, setCaseSearch] = useState('');
  const [dialog, setDialog] = useState<'new' | 'help' | null>(null);
  const [newName, setNewName] = useState('');
  const [newType, setNewType] = useState('Residencia inicial');
  const [doc, setDoc] = useState<number | null>(null);
  const [docNote, setDocNote] = useState('');
  const [docNotes, setDocNotes] = useState<Record<number, string>>({});
  const [selectedChat, setSelectedChat] = useState(0);
  const [message, setMessage] = useState('');
  const [messages, setMessages] = useState<Record<number, string[]>>({});
  const [exception, setException] = useState<Record<string, string>>({});
  const [exceptionModal, setExceptionModal] = useState(false);
  const [reason, setReason] = useState('Comprobar con el cliente una particularidad de la documentación antes de continuar.');
  const active = [...nav].reverse().find(n => pathname === n.path || (n.path !== '/gestion' && pathname.startsWith(`${n.path}/`))) || nav[0];
  const isEditor = pathname === '/gestion/rutas/residencia-demo';
  const isDetail = pathname.startsWith('/gestion/expedientes/');
  const currentCase = cases.find(c => pathFor(c) === pathname);
  const notify = (message: string) => setToast(message);
  useEffect(() => { window.scrollTo(0, 0); setMobileMenu(false); setFilter('Todos'); setCaseSearch(''); setSearch(''); setNotification(false); }, [pathname]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 4500); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { document.title = `${isEditor ? 'Residencia inicial' : active.label} · AS Workspace`; }, [active.label, isEditor]);
  const matching = cases.filter(c => normalizeSearch(`${c.name} ${c.id} ${c.type}`).includes(normalizeSearch(search)));
  const selectedDoc = documents.find(d => d.id === doc);
  const completedSteps = currentCase ? (currentCase.id === 'AS-0187' ? 3 : currentCase.stage === 'Entrevista' ? 0 : currentCase.stage === 'Documentación' ? 1 : currentCase.stage === 'Presentación' ? 3 : currentCase.stage === 'Resolución' ? 4 : 2) : 0;
  const remaining = tasks.filter(t => !t.done).length;
  const unread = [0, 1].filter(id => !messages[id]?.length).length;
  const caseTable = (rows: Case[]) => <div className="crm-table-wrap"><table className="crm-table"><thead><tr><th>Cliente / expediente</th><th>Trámite</th><th>Estado</th><th>Responsable</th><th>Próxima acción</th><th /></tr></thead><tbody>{rows.map(c => <tr key={c.id}><td><Link className="crm-person crm-person-link" to={pathFor(c)}><Avatar name={c.name} color={c.color} /><span><strong>{c.name}</strong><small>{c.id}</small></span></Link></td><td>{c.type}</td><td><Badge tone={c.stage === 'Documentación' ? 'amber' : c.stage === 'Resolución' ? 'green' : 'blue'}>{c.stage}</Badge></td><td><span className="crm-owner"><Avatar name={c.owner} color={c.owner === 'Marta Pérez' ? 1 : 2} />{c.owner}</span></td><td><span className={c.date === 'Hoy' ? 'crm-due' : ''}>{c.date}</span></td><td><Link className="crm-icon-button" to={pathFor(c)} aria-label={`Abrir expediente de ${c.name}`}><Glyph name="chevron" size={16} /></Link></td></tr>)}</tbody></table>{!rows.length && <div className="crm-empty"><Glyph name="search" size={28} /><h3>No hay expedientes con estos filtros</h3><p>Prueba otro nombre, identificador o estado.</p><button className="crm-btn" onClick={() => { setFilter('Todos'); setCaseSearch(''); }}>Limpiar filtros</button></div>}</div>;
  const taskRows = (all = true) => <div className="crm-task-list">{tasks.filter(t => all || !t.done).map(t => <label className={`crm-task ${t.done ? 'is-done' : ''}`} key={t.id}><input type="checkbox" checked={t.done} onChange={() => setTasks(list => list.map(x => x.id === t.id ? { ...x, done: !x.done } : x))} /><span><strong>{t.title}</strong><small>{t.caseId} · {t.owner}</small></span><Badge tone={t.priority === 'Alta' && !t.done ? 'amber' : 'neutral'}>{t.done ? 'Completada' : t.time}</Badge></label>)}</div>;
  return <div className="crm-app">
    <a className="crm-skip" href="#crm-contenido" onClick={e => { e.preventDefault(); document.getElementById('crm-contenido')?.focus(); }}>Saltar al contenido</a>
    {mobileMenu && <button className="crm-sidebar-scrim" aria-label="Cerrar menú" onClick={() => setMobileMenu(false)} />}
    <aside inert={compact && !mobileMenu} id="crm-navigation" className={`crm-sidebar ${mobileMenu ? 'is-open' : ''}`}><Link className="crm-brand" to="/gestion"><img src={logo} alt="Antonio Segura Abogados y Gestores" /><span>WORKSPACE</span></Link><div className="crm-workspace"><span className="crm-workspace-symbol">AS</span><span><strong>Despacho Barcelona</strong><small>Espacio de trabajo</small></span><Glyph name="lock" size={14} /></div><nav aria-label="Navegación del CRM">{nav.map(n => <div key={n.path}>{n.group && <span className="crm-nav-group">{n.group}</span>}<NavLink end={n.path === '/gestion'} to={n.path} className={({ isActive }) => isActive ? 'is-active' : ''}><Glyph name={n.icon} /><span>{n.label}</span>{n.count && <b>{n.icon === 'tasks' ? remaining : n.icon === 'chat' ? unread : n.icon === 'history' ? (changeApplied ? 0 : 1) : n.count}</b>}</NavLink></div>)}</nav><div className="crm-sidebar-bottom"><div className="crm-demo-card"><span><i />Entorno de demostración</span><p>Una visión del despacho conectado.</p><button onClick={() => setDialog('help')}>Explorar la propuesta<Glyph name="arrow" size={15} /></button></div><button className="crm-user" onClick={() => navigate('/gestion/equipo')}><Avatar name="Marta Pérez" color={1} /><span><strong>Marta Pérez</strong><small>Administradora</small></span><Glyph name="settings" size={17} /></button></div></aside>
    <div className="crm-main"><header className="crm-topbar"><button className="crm-icon-button crm-menu-toggle" onClick={() => setMobileMenu(!mobileMenu)} aria-label="Abrir menú" aria-controls="crm-navigation" aria-expanded={mobileMenu}><Glyph name="menu" /></button><div className="crm-breadcrumb"><span>Workspace</span><Glyph name="chevron" size={12} /><Link to={active.path}>{active.label}</Link>{isEditor && <><Glyph name="chevron" size={12} /><strong>Residencia inicial</strong></>}{isDetail && currentCase && <><Glyph name="chevron" size={12} /><strong>{currentCase.id}</strong></>}</div><div className="crm-global-search"><Glyph name="search" size={17} /><input aria-label="Buscar en el CRM" placeholder="Buscar clientes, expedientes…" value={search} onChange={e => { setSearch(e.target.value); setNotification(false); }} onKeyDown={e => { if (e.key === 'Escape') setSearch(''); }} />{search && <div className="crm-search-results"><span>EXPEDIENTES</span>{matching.length ? matching.map(c => <Link key={c.id} to={pathFor(c)} onClick={() => setSearch('')}><Avatar name={c.name} color={c.color} /><span><strong>{c.name}</strong><small>{c.id} · {c.type}</small></span><Glyph name="arrow" size={16} /></Link>) : <p>No se han encontrado expedientes.</p>}</div>}</div><div className="crm-top-actions"><span className="crm-demo-label"><i />Demo</span><button className="crm-icon-button crm-notification-button" aria-label="Notificaciones" aria-expanded={notification} onClick={() => { setNotification(!notification); setSearch(''); }}><Glyph name="bell" /><i /></button><Avatar name="Marta Pérez" color={1} /></div>{notification && <div className="crm-notifications"><h3>Actividad reciente</h3><Link to="/gestion/documentos"><Glyph name="file" /><span><strong>Lucía ha subido 2 documentos</strong><small>Hace 12 minutos · Pendientes de revisión</small></span></Link><Link to="/gestion/cambios"><Glyph name="history" /><span><strong>Una versión lista para revisar</strong><small>Residencia inicial · Versión 2</small></span></Link><Link to="/gestion/mensajes"><Glyph name="chat" /><span><strong>Nuevas conversaciones</strong><small>El equipo tiene 2 mensajes por atender</small></span></Link></div>}</header>
    <main id="crm-contenido" className="crm-content" tabIndex={-1}>
      <div hidden={!isEditor}><RouteEditor notify={notify} migrated={changeApplied} /></div>
      <div hidden={pathname !== '/gestion/cambios'}><Changes notify={notify} onApply={() => setChangeApplied(true)} /></div>
      {isEditor || pathname === '/gestion/cambios' ? null : pathname === '/gestion' ? <>
        <PageHeading title="Buenos días, Marta" text="Viernes, 18 de septiembre de 2026 · Tu despacho, de un vistazo." action={<button className="crm-btn crm-btn--primary" onClick={() => setDialog('new')}><Glyph name="plus" />Nuevo expediente</button>} />
        <div className="crm-metrics"><div><span>Expedientes activos<Glyph name="cases" /></span><strong>{cases.length}<small>4 tipologías de trámite</small></strong></div><div><span>Tareas para hoy<Glyph name="tasks" /></span><strong>{remaining}<small>{tasks.filter(t => !t.done && t.priority === 'Alta').length} de prioridad alta</small></strong></div><div><span>Documentos por revisar<Glyph name="file" /></span><strong>{documents.filter(d => d.state === 'Pendiente').length}<small>Recibidos esta mañana</small></strong></div><div><span>Conversaciones pendientes<Glyph name="chat" /></span><strong>{unread}<small>Atención al cliente</small></strong></div></div>
        <div className="crm-dashboard-grid"><section className="crm-card"><div className="crm-card-title"><div><span className="crm-overline">TU DÍA, ORGANIZADO</span><h2>Lo que necesita tu atención</h2></div><Link className="crm-text-btn" to="/gestion/tareas">Ver agenda<Glyph name="arrow" size={16} /></Link></div>{taskRows(false)}{remaining === 0 && <p className="crm-empty">Todo al día. Has completado las tareas de esta muestra.</p>}</section><section className="crm-card crm-pipeline"><div className="crm-card-title"><h2>Estado de los expedientes</h2><Glyph name="cases" /></div>{['Entrevista', 'Documentación', 'Revisión jurídica', 'Presentación', 'Resolución'].map((s, i) => <div className="crm-pipeline-row" key={s}><span><i style={{ background: ['#a2b5c4', '#e6ad57', '#9a8acd', '#51a6db', '#69a98f'][i] }} />{s}</span><b>{cases.filter(c => c.stage === s).length}</b><div><i style={{ width: `${cases.filter(c => c.stage === s).length / cases.length * 100}%`, background: ['#a2b5c4', '#e6ad57', '#9a8acd', '#51a6db', '#69a98f'][i] }} /></div></div>)}</section></div>
        <section className="crm-card"><div className="crm-card-title"><h2>Expedientes en seguimiento</h2><Link className="crm-text-btn" to="/gestion/expedientes">Ver todos<Glyph name="arrow" size={16} /></Link></div>{caseTable(cases.slice(0, 4))}</section>
      </> : pathname === '/gestion/expedientes' ? <>
        <PageHeading title="Expedientes" text="Toda la información del cliente, cada paso y la siguiente acción." action={<button className="crm-btn crm-btn--primary" onClick={() => setDialog('new')}><Glyph name="plus" />Nuevo expediente</button>} />
        <div className="crm-tabs" role="tablist" aria-label="Filtrar expedientes">{['Todos', 'Documentación', 'Revisión jurídica', 'Resolución'].map(f => <button key={f} role="tab" aria-selected={filter === f} onClick={() => setFilter(f)}>{f}<span>{cases.filter(c => f === 'Todos' || c.stage === f).length}</span></button>)}</div>
        <section className="crm-card"><div className="crm-table-tools"><div className="crm-table-search"><Glyph name="search" size={17} /><input aria-label="Buscar expediente" placeholder="Buscar por nombre o expediente" value={caseSearch} onChange={e => setCaseSearch(e.target.value)} /></div><span className="crm-muted"><Glyph name="filter" size={16} />Todos los responsables</span></div>{caseTable(cases.filter(c => (filter === 'Todos' || c.stage === filter) && normalizeSearch(`${c.name} ${c.id}`).includes(normalizeSearch(caseSearch))))}<div className="crm-table-footer"><span>{cases.length} expedientes en esta muestra</span><span>Página 1 de 1</span></div></section>
      </> : isDetail ? currentCase ? <>
        <div className="crm-detail-back"><Link to="/gestion/expedientes">← Todos los expedientes</Link><Badge>{currentCase.id}</Badge></div><PageHeading title={currentCase.name} text={`${currentCase.type} · Apertura el ${currentCase.opened || '02 sep. 2026'} · Responsable: ${currentCase.owner}`} action={<button className="crm-btn" onClick={() => { setReason(exception[currentCase.id] || 'Comprobar con el cliente una particularidad de la documentación antes de continuar.'); setExceptionModal(true); }}><Glyph name="plus" />{exception[currentCase.id] ? 'Editar excepción' : 'Añadir excepción'}</button>} />
        <div className="crm-case-detail-grid"><section className="crm-card"><div className="crm-card-title"><h2>Recorrido del expediente</h2><Badge tone="blue">Versión {changeApplied && currentCase.id === 'AS-0142' ? 2 : 1}</Badge></div><div className="crm-case-journey">{['Entrevista inicial', 'Preparar documentación', ...(exception[currentCase.id] ? ['Comprobación adicional'] : []), 'Revisión del equipo', 'Presentación del trámite', 'Seguimiento de resolución'].map((s, i) => <div key={s} className={s === 'Comprobación adicional' ? 'is-exception' : ''}><span className={i < completedSteps && s !== 'Comprobación adicional' ? 'is-complete' : ''}>{i < completedSteps && s !== 'Comprobación adicional' ? <Glyph name="check" size={16} /> : i + 1}</span><div><strong>{s}</strong><small>{s === 'Comprobación adicional' ? exception[currentCase.id] : i < completedSteps ? 'Completado · avance conservado' : i === completedSteps ? 'Paso actual · pendiente de completar' : 'Pendiente'}</small></div>{s === 'Comprobación adicional' && <Badge tone="amber">Solo este caso</Badge>}</div>)}</div><div className="crm-info"><Glyph name="lock" /><span>Las excepciones de este expediente no modifican la plantilla ni los demás casos.</span></div></section><aside className="crm-card"><div className="crm-card-title"><h2>Ficha del cliente</h2></div><div className="crm-client-card"><Avatar name={currentCase.name} color={currentCase.color} /><h3>{currentCase.name}</h3><Badge tone="green">Cliente activo</Badge></div><dl className="crm-contact-info"><div><dt>Expediente</dt><dd>{currentCase.id}</dd></div><div><dt>Trámite</dt><dd>{currentCase.type}</dd></div><div><dt>Responsable</dt><dd>{currentCase.owner}</dd></div><div><dt>Prioridad</dt><dd>{currentCase.priority}</dd></div></dl><Link className="crm-btn" to="/gestion/documentos"><Glyph name="file" />Abrir carpeta documental</Link></aside></div>
        {exceptionModal && <Modal title="Excepción individual" close={() => setExceptionModal(false)}><p>Se añadirá una comprobación entre documentación y revisión, únicamente para {currentCase.name}.</p><label className="crm-field">Motivo e instrucciones<textarea rows={4} maxLength={400} value={reason} onChange={e => setReason(e.target.value)} /></label><div className="crm-modal-actions"><button className="crm-btn" onClick={() => setExceptionModal(false)}>Cancelar</button><button className="crm-btn crm-btn--primary" disabled={!reason.trim()} onClick={() => { setException(values => ({ ...values, [currentCase.id]: reason.trim() })); setExceptionModal(false); notify(`Excepción guardada en ${currentCase.id}.`); }}>Guardar excepción</button></div></Modal>}
      </> : <div className="crm-empty"><h1>Expediente no encontrado</h1><Link to="/gestion/expedientes">Volver a los expedientes</Link></div> : pathname === '/gestion/tareas' ? <>
        <PageHeading title="Tareas y agenda" text="Prioridades claras, responsables definidos y contexto en cada tarea." action={<Badge tone="blue">Viernes · 18 septiembre</Badge>} /><div className="crm-dashboard-grid"><section className="crm-card"><div className="crm-card-title"><h2>Agenda del equipo</h2><Badge>{remaining} pendientes</Badge></div>{taskRows()}</section><section className="crm-card"><div className="crm-card-title"><h2>Próximas citas</h2><Glyph name="calendar" /></div>{[['10:00', 'Consulta de seguimiento', 'Lucía Martínez · Marta Pérez'], ['12:00', 'Revisión del caso', 'Omar Benali · Carlos Vidal'], ['16:30', 'Primera entrevista', 'Andrés Molina · Laura Costa']].map(([time, title, person]) => <div className="crm-appointment" key={time}><span>{time}</span><div><h3>{title}</h3><p>{person}</p><Badge>30 min · Videollamada</Badge></div></div>)}</section></div>
      </> : pathname === '/gestion/documentos' ? <>
        <PageHeading title="Documentos" text="Una bandeja de revisión conectada a cada expediente." /><div className="crm-tabs" role="tablist" aria-label="Filtrar documentos">{['Todos', 'Pendiente', 'Validado', 'Subsanación'].map(f => <button key={f} role="tab" aria-selected={filter === f} onClick={() => setFilter(f)}>{f}<span>{documents.filter(d => f === 'Todos' || d.state === f).length}</span></button>)}</div><section className="crm-card"><div className="crm-table-wrap"><table className="crm-table"><thead><tr><th>Documento</th><th>Cliente</th><th>Recibido</th><th>Estado</th><th /></tr></thead><tbody>{documents.filter(d => filter === 'Todos' || d.state === filter).map(d => <tr key={d.id}><td><div className="crm-person"><span className="crm-file-icon"><Glyph name="file" /></span><span><strong>{d.name}</strong><small>PDF · {d.size}</small></span></div></td><td>{d.person}<small className="crm-cell-note">{d.caseId}</small></td><td>{d.date}</td><td><Badge tone={d.state === 'Validado' ? 'green' : 'amber'}>{d.state}</Badge></td><td><button className="crm-text-btn" onClick={() => { setDoc(d.id); setDocNote(docNotes[d.id] || ''); }}>Revisar<Glyph name="arrow" size={15} /></button></td></tr>)}</tbody></table>{!documents.some(d => filter === 'Todos' || d.state === filter) && <div className="crm-empty"><Glyph name="check" size={28} /><h3>No hay documentos en este estado</h3><p>La bandeja se actualizará al revisar los documentos.</p></div>}</div></section>
      </> : pathname === '/gestion/mensajes' ? <>
        <PageHeading title="Conversaciones" text="Atención cercana, con todo el contexto del expediente." /><section className="crm-inbox crm-card"><aside className="crm-chat-list"><div className="crm-panel-heading"><h2>Bandeja del equipo</h2><Badge tone="blue">{unread}</Badge></div>{cases.slice(0, 3).map((c, i) => <button className={selectedChat === i ? 'is-selected' : ''} onClick={() => setSelectedChat(i)} key={c.id}><Avatar name={c.name} color={c.color} /><span><strong>{c.name}</strong><small>{i === 0 ? 'Ya he adjuntado el pasaporte.' : i === 1 ? '¿Cuál será el siguiente paso?' : 'Muchas gracias por la ayuda.'}</small></span>{i < 2 && !messages[i]?.length && <i />}</button>)}</aside><div className="crm-chat"><div className="crm-chat-heading"><div className="crm-person"><Avatar name={cases[selectedChat].name} color={selectedChat} /><span><strong>{cases[selectedChat].name}</strong><small>{cases[selectedChat].id} · {cases[selectedChat].type}</small></span></div><Link className="crm-text-btn" to={pathFor(cases[selectedChat])}>Ver expediente<Glyph name="arrow" size={15} /></Link></div><div className="crm-chat-messages"><span className="crm-chat-date">Hoy, 18 de septiembre</span><div className="crm-bubble crm-bubble--out">Hola, {cases[selectedChat].name.split(' ')[0]}. Soy Marta, tu gestora. Te acompaño con los siguientes pasos de tu expediente.<small>09:02 · Marta Pérez</small></div><div className="crm-bubble">{selectedChat === 0 ? '¡Buenos días! Ya he adjuntado el pasaporte y el certificado. ¿Podéis comprobar que esté todo bien?' : selectedChat === 1 ? 'Hola, ¿cuál será el siguiente paso una vez revisada la documentación?' : 'Muchas gracias por la ayuda. Quedo pendiente de la presentación.'}<small>09:14</small></div>{messages[selectedChat]?.map((m, i) => <div className="crm-bubble crm-bubble--out" key={i}>{m}<small>Ahora · Envío simulado</small></div>)}</div><form className="crm-chat-compose" onSubmit={e => { e.preventDefault(); if (!message.trim()) return; setMessages(all => ({ ...all, [selectedChat]: [...(all[selectedChat] || []), message.trim()] })); setMessage(''); }}><label className="crm-sr-only" htmlFor="crm-message">Escribir respuesta</label><textarea id="crm-message" rows={2} placeholder="Escribe una respuesta…" value={message} onChange={e => setMessage(e.target.value)} maxLength={1200} /><div><small><Glyph name="lock" size={13} />Conversación de ejemplo · sin envío real</small><button className="crm-btn crm-btn--primary" disabled={!message.trim()}>Enviar respuesta<Glyph name="arrow" size={16} /></button></div></form></div></section>
      </> : pathname === '/gestion/rutas' ? <>
        <PageHeading title="Rutas de trabajo" text="El criterio del despacho convertido en procesos claros y repetibles." action={<Link className="crm-btn crm-btn--primary" to="/gestion/rutas/residencia-demo"><Glyph name="route" />Abrir configurador</Link>} /><div className="crm-route-catalog">{routeNames.map((name, i) => <article className="crm-card crm-route-card" key={name}><div className="crm-route-card-top"><span className="crm-square-icon"><Glyph name="route" size={24} /></span><Badge tone={i === 0 ? 'green' : 'neutral'}>{i === 0 ? 'Activa' : 'Plantilla de muestra'}</Badge></div><h2>{name}</h2><p>{['Del estudio inicial al seguimiento de la resolución.', 'Documentación, preparación y seguimiento del proceso.', 'Un recorrido ordenado para preparar la renovación.', 'Coordinación documental y acompañamiento familiar.'][i]}</p><div className="crm-route-card-meta"><span>{i === 0 ? '5 pasos · 2 expedientes' : 'Configuración pendiente'}</span><span>v1</span></div>{i === 0 ? <Link className="crm-btn" to="/gestion/rutas/residencia-demo">Editar ruta<Glyph name="arrow" size={16} /></Link> : <button className="crm-btn" onClick={() => notify(`«${name}» es una plantilla ilustrativa. Explora el editor completo en Residencia inicial.`)}>Ver alcance<Glyph name="eye" size={16} /></button>}</article>)}</div>
      </> : pathname === '/gestion/equipo' ? <>
        <PageHeading title="Equipo del despacho" text="Responsabilidades y carga de trabajo en un mismo lugar." action={<Badge tone="blue">3 profesionales · muestra</Badge>} /><div className="crm-team-grid">{[['Marta Pérez', 'Administradora · Gestora', 'MP'], ['Carlos Vidal', 'Responsable jurídico', 'CV'], ['Laura Costa', 'Gestora de expedientes', 'LC']].map(([name, role], i) => <article className="crm-card crm-team-card" key={name}><Avatar name={name} color={i + 1} /><h2>{name}</h2><p>{role}</p><Badge tone="green">Disponible</Badge><div className="crm-team-stats"><span><strong>{cases.filter(c => c.owner === name).length}</strong>Expedientes</span><span><strong>{tasks.filter(t => t.owner === name && !t.done).length}</strong>Tareas pendientes</span></div><div className="crm-team-permissions"><Glyph name="lock" size={16} /><span>{i === 0 ? 'Gestión, configuración y publicación' : i === 1 ? 'Revisión jurídica y validación de versiones' : 'Gestión documental y atención al cliente'}</span></div></article>)}</div><div className="crm-info"><Glyph name="team" /><span>Perfiles, nombres y asignaciones ficticios para mostrar la organización del backoffice.</span></div>
      </> : <div className="crm-empty"><h1>Vista no disponible</h1><Link to="/gestion">Volver a la vista general</Link></div>}
      <footer className="crm-footer"><span>AS Workspace <i /> Propuesta de Pol Surriel · Datos ficticios</span><div><button onClick={reset}>Reiniciar demo</button><Link to="/demos">Todas las demos<Glyph name="arrow" size={13} /></Link></div></footer>
    </main></div>
    {toast && <div className="crm-toast" role="status"><Glyph name="check" /><span>{toast}</span><button onClick={() => setToast('')} aria-label="Cerrar aviso"><Glyph name="close" size={16} /></button></div>}
    {dialog === 'help' && <Modal title="Un despacho conectado" close={() => setDialog(null)}><p>Esta propuesta reúne la gestión del cliente, el trabajo del equipo y la configuración de los procesos en un único backoffice.</p><div className="crm-help-links">{nav.slice(0, 7).map(n => <Link to={n.path} key={n.path} onClick={() => setDialog(null)}><Glyph name={n.icon} />{n.label}<Glyph name="arrow" size={16} /></Link>)}</div><p className="crm-modal-note">Demo interactiva con datos ficticios. Los cambios duran durante esta sesión; recargar o reiniciar restaura la muestra.</p></Modal>}
    {dialog === 'new' && <Modal title="Nuevo expediente" close={() => setDialog(null)}><form onSubmit={e => { e.preventDefault(); if (!newName.trim()) return; const next: Case = { id: `AS-${String(232 + cases.length - initialCases.length).padStart(4, '0')}`, name: newName.trim(), opened: '18 sep. 2026', type: newType, stage: 'Entrevista', owner: 'Marta Pérez', date: 'Hoy', priority: 'Media', progress: 0, color: cases.length % 4 }; setCases(list => [...list, next]); setNewName(''); setDialog(null); navigate(pathFor(next)); notify('Expediente de ejemplo creado.'); }}><label className="crm-field">Nombre del cliente<input required autoFocus maxLength={70} placeholder="Nombre y apellidos de ejemplo" value={newName} onChange={e => setNewName(e.target.value)} /></label><label className="crm-field">Trámite<select value={newType} onChange={e => setNewType(e.target.value)}>{routeNames.map(n => <option key={n}>{n}</option>)}</select></label><div className="crm-info"><Glyph name="team" /><span>Se asignará a Marta Pérez, comenzando por la entrevista inicial.</span></div><div className="crm-modal-actions"><button type="button" className="crm-btn" onClick={() => setDialog(null)}>Cancelar</button><button type="submit" className="crm-btn crm-btn--primary" disabled={!newName.trim()}>Crear expediente de ejemplo</button></div></form></Modal>}
    {selectedDoc && <Modal title="Revisión documental" close={() => setDoc(null)}><div className="crm-document-sheet"><Glyph name="file" size={48} /><h3>{selectedDoc.name}</h3><p>{selectedDoc.person} · {selectedDoc.caseId}</p><Badge tone="blue">Documento de muestra</Badge><small>Vista ilustrativa. No contiene documentos personales.</small></div><label className="crm-field">Observaciones del equipo<textarea rows={3} value={docNote} maxLength={400} onChange={e => setDocNote(e.target.value)} placeholder="Indica qué debe corregirse o deja una nota de revisión…" /></label><div className="crm-modal-actions"><button className="crm-btn" disabled={!docNote.trim()} onClick={() => { setDocuments(all => all.map(d => d.id === doc ? { ...d, state: 'Subsanación' } : d)); setDocNotes(all => ({ ...all, [selectedDoc.id]: docNote.trim() })); setDoc(null); notify('Subsanación registrada en la demo.'); }}>Solicitar subsanación</button><button className="crm-btn crm-btn--primary" onClick={() => { setDocuments(all => all.map(d => d.id === doc ? { ...d, state: 'Validado' } : d)); setDocNotes(all => ({ ...all, [selectedDoc.id]: docNote.trim() })); setDoc(null); notify('Documento validado en la demo.'); }}><Glyph name="check" />Validar documento</button></div></Modal>}
  </div>;
}
