import { useState } from 'react';
import { Link } from 'react-router';
import data from '../../../../recursos-compartidos/demo/gestion.json';
import { Badge, Glyph, Modal } from './ui';

type Step = typeof data.ruta.pasos[number] & { owner?: string; required?: boolean; documents?: string[]; reminder?: boolean };
const initial: Step[] = data.ruta.pasos.map(s => ({ ...s, owner: s.id === 'revision' ? 'Responsable jurídico' : 'Gestor del expediente', required: true, reminder: true, documents: s.id === 'documentos' ? ['Documento de identidad', 'Documentación del trámite'] : [] }));
export function RouteEditor({ notify, migrated }: { notify: (message: string) => void; migrated: boolean }) {
  const [steps, setSteps] = useState(initial);
  const [selected, setSelected] = useState('documentos');
  const [tab, setTab] = useState('Constructor');
  const [published, setPublished] = useState(false);
  const [dirty, setDirty] = useState(false);
  const [modal, setModal] = useState<'publish' | 'preview' | 'add' | null>(null);
  const [date, setDate] = useState('2026-10-01');
  const [reviewed, setReviewed] = useState(false);
  const [newName, setNewName] = useState('');
  const [newDoc, setNewDoc] = useState('');
  const step = steps.find(s => s.id === selected)!;
  const index = steps.findIndex(s => s.id === selected);
  function edit(change: Partial<Step>) { setSteps(items => items.map(s => s.id === selected ? { ...s, ...change } : s)); setDirty(true); setReviewed(false); }
  function move(direction: number) { const next = [...steps]; [next[index], next[index + direction]] = [next[index + direction], next[index]]; setSteps(next); setDirty(true); setReviewed(false); }
  const valid = steps.every(s => s.titulo.trim() && s.instruccion.trim());
  const preview = <div className="crm-client-preview"><div className="crm-phone-top"><span>9:41</span><i /><span>▮▮ ▰</span></div><div className="crm-phone-body"><div className="crm-phone-brand"><b>AS<span>ABOGADOS</span></b><span className="crm-avatar">LM</span></div><p className="crm-phone-greeting">Hola, Lucía</p><h3>Un paso más cerca.</h3><div className="crm-phone-progress"><span>Tu residencia</span><b>{index + 1} de {steps.length}</b><i><span style={{ width: `${(index + 1) / steps.length * 100}%` }} /></i></div><div className="crm-phone-action"><span className="crm-overline">TU SIGUIENTE PASO</span><div className="crm-phone-icon"><Glyph name={step.tipo === 'Documentos' ? 'file' : 'tasks'} size={24} /></div><h4>{step.titulo || 'Nombre del paso'}</h4><p>{step.instruccion || 'Las instrucciones aparecerán aquí.'}</p>{step.documents?.map(d => <div className="crm-phone-doc" key={d}><Glyph name="file" size={14} />{d}</div>)}<span className="crm-phone-cta">{step.tipo === 'Documentos' ? 'Preparar documentos' : 'Ver mi siguiente paso'}<Glyph name="arrow" size={14} /></span></div><div className="crm-phone-support"><span className="crm-avatar crm-avatar--1">MP</span><span><strong>Marta, tu gestora</strong><small>Te acompañamos en cada paso</small></span></div></div><div className="crm-phone-nav"><Glyph name="grid" /><Glyph name="file" /><Glyph name="chat" /><Glyph name="team" /></div><div className="crm-phone-bottom" /></div>;
  return <>
    <div className="crm-page-heading"><div><div className="crm-title-line"><h1>Residencia inicial</h1><Badge tone={published ? 'green' : 'amber'}>{published ? 'Publicada · v2' : 'Borrador · v2'}</Badge></div><p>Diseña el recorrido del cliente y coordina el trabajo del equipo.</p></div><div className="crm-actions"><button className="crm-btn" onClick={() => setModal('preview')}><Glyph name="eye" />Vista previa</button><button className="crm-btn crm-btn--primary" disabled={published || !valid} onClick={() => setModal('publish')}><Glyph name="check" />{published ? 'Versión publicada' : 'Publicar versión'}</button></div></div>
    <div className="crm-route-meta"><span><Glyph name="route" size={16} />{steps.length} pasos</span><span><Glyph name="cases" size={16} />2 expedientes vinculados</span><span><span className="crm-online-dot" />Versión 1 en producción</span><span className="crm-meta-end"><Glyph name="clock" size={15} />{published ? 'Publicación registrada en esta sesión' : dirty ? 'Cambios sin guardar' : 'Borrador guardado en esta sesión'}</span></div>
    <div className="crm-tabs" role="tablist" aria-label="Configuración de la ruta">{['Constructor', 'Reglas y automatizaciones', 'Historial de versiones', 'Expedientes vinculados'].map(t => <button role="tab" aria-selected={tab === t} key={t} onClick={() => setTab(t)}>{t}{t === 'Constructor' && <span>{steps.length}</span>}</button>)}</div>
    {tab === 'Constructor' && <><div className="crm-builder" data-capture="board">
      <section className="crm-step-panel"><div className="crm-panel-heading"><h2>Pasos de la ruta</h2><Badge>{steps.length}</Badge></div><p className="crm-muted">El recorrido, de principio a fin.</p><ol className="crm-steps">{steps.map((s, i) => <li key={s.id}><button className={selected === s.id ? 'is-selected' : ''} aria-pressed={selected === s.id} onClick={() => setSelected(s.id)}><span className="crm-step-number">{String(i + 1).padStart(2, '0')}</span><span><strong>{s.titulo}</strong><small>{s.tipo}</small></span>{selected === s.id && <Glyph name="chevron" size={14} />}</button></li>)}</ol><button className="crm-add-step" disabled={published} onClick={() => setModal('add')}><Glyph name="plus" size={16} />Añadir paso</button><div className="crm-step-note"><Glyph name="lock" size={16} /><p>La versión publicada se mantiene hasta aprobar este borrador.</p></div></section>
      <section className="crm-step-editor"><div className="crm-editor-heading"><div><span className="crm-overline">PASO {String(index + 1).padStart(2, '0')}</span><h2>{step.titulo || 'Nuevo paso'}</h2></div><span className="crm-square-icon"><Glyph name={step.tipo === 'Documentos' ? 'file' : 'tasks'} /></span></div><fieldset disabled={published}><label className="crm-field">Nombre del paso<input maxLength={64} value={step.titulo} onChange={e => edit({ titulo: e.target.value })} /></label><div className="crm-field-row"><label className="crm-field">Tipo de paso<select value={step.tipo} onChange={e => edit({ tipo: e.target.value })}>{['Formulario', 'Documentos', 'Revisión profesional', 'Gestión del despacho', 'Seguimiento'].map(t => <option key={t}>{t}</option>)}</select></label><label className="crm-field">Responsable<select value={step.owner} onChange={e => edit({ owner: e.target.value })}><option>Gestor del expediente</option><option>Responsable jurídico</option><option>Atención al cliente</option></select></label></div><label className="crm-field"><span>Instrucciones para el cliente<Badge tone="blue">Visible en la app</Badge></span><textarea rows={4} maxLength={400} value={step.instruccion} onChange={e => edit({ instruccion: e.target.value })} /><small>Explica qué necesita hacer y cómo le acompañaremos.<span>{step.instruccion.length}/400</span></small></label>
      {step.tipo === 'Documentos' && <div className="crm-doc-config"><div className="crm-section-label"><h3>Documentos solicitados</h3><span>{step.documents?.length || 0}</span></div>{step.documents?.map(d => <div className="crm-config-doc" key={d}><span className="crm-file-icon"><Glyph name="file" size={17} /></span><span>{d}<small>Copia digital · revisión del equipo</small></span><button className="crm-icon-button" onClick={() => edit({ documents: step.documents?.filter(x => x !== d) })} aria-label={`Quitar ${d}`}><Glyph name="close" size={14} /></button></div>)}<form className="crm-inline-form" onSubmit={e => { e.preventDefault(); const value = newDoc.trim(); if (value && !step.documents?.includes(value)) { edit({ documents: [...(step.documents || []), value] }); setNewDoc(''); } }}><input aria-label="Nombre del documento solicitado" placeholder="Añadir documento…" value={newDoc} maxLength={70} onChange={e => setNewDoc(e.target.value)} /><button type="submit" className="crm-icon-button" aria-label="Añadir documento" disabled={!newDoc.trim() || step.documents?.includes(newDoc.trim())}><Glyph name="plus" size={17} /></button></form></div>}
      <label className="crm-toggle-row"><span><strong>Revisión obligatoria del equipo</strong><small>Validar este paso antes de avanzar al siguiente.</small></span><input type="checkbox" role="switch" checked={step.required} onChange={e => edit({ required: e.target.checked })} /></label><div className="crm-editor-order"><span>Posición {index + 1} de {steps.length}</span><div><button className="crm-btn crm-btn--small" disabled={index === 0 || published} onClick={() => move(-1)}>↑ Subir</button><button className="crm-btn crm-btn--small" disabled={index === steps.length - 1 || published} onClick={() => move(1)}>↓ Bajar</button></div></div></fieldset></section>
      <aside className="crm-preview-panel"><div className="crm-panel-heading"><h2>Vista del cliente</h2><Glyph name="eye" size={16} /></div><p className="crm-muted">Así lo verá Lucía en su app.</p>{preview}<span className="crm-preview-caption"><span className="crm-online-dot" />Vista previa en tiempo real</span></aside>
    </div><div className="crm-builder-footer"><span><Glyph name="lock" size={16} />Los expedientes abiertos conservan su versión y su progreso.</span><button className="crm-btn" disabled={published || !valid || !dirty} onClick={() => { setDirty(false); notify('Borrador guardado durante esta sesión.'); }}><Glyph name="check" size={16} />Guardar borrador</button></div></>}
    {tab === 'Reglas y automatizaciones' && <div className="crm-card crm-rule-list"><div className="crm-card-title"><div><h2>Un proceso que acompaña al equipo</h2><p>Reglas del paso seleccionado: {step.titulo}.</p></div><Badge tone="blue">Configuración de ejemplo</Badge></div><label className="crm-toggle-row"><span><strong>Recordatorio de documentación</strong><small>A los 3 días sin actividad, preparar un recordatorio para el gestor.</small></span><input type="checkbox" role="switch" disabled={published} checked={step.reminder} onChange={e => edit({ reminder: e.target.checked })} /></label><label className="crm-toggle-row"><span><strong>Validación antes de avanzar</strong><small>El responsable debe revisar y completar el paso.</small></span><input type="checkbox" role="switch" disabled={published} checked={step.required} onChange={e => edit({ required: e.target.checked })} /></label><div className="crm-info"><Glyph name="spark" /><span>Las reglas forman parte del borrador. En esta demo no se envían recordatorios.</span></div></div>}
    {tab === 'Historial de versiones' && <div className="crm-card"><div className="crm-card-title"><h2>Historial de la ruta</h2><Badge>2 versiones</Badge></div><div className="crm-version-row"><span className="crm-square-icon"><Glyph name="route" /></span><div><h3>Versión 2 · Instrucciones documentales</h3><p>Marta Pérez · 18 sep. 2026 · {steps.length} pasos</p></div><Badge tone={published ? 'green' : 'amber'}>{published ? 'Publicada' : 'Borrador'}</Badge></div><div className="crm-version-row"><span className="crm-square-icon"><Glyph name="check" /></span><div><h3>Versión 1 · Ruta inicial</h3><p>Carlos Vidal · 02 sep. 2026 · 2 expedientes vinculados</p></div><Badge tone="green">En uso</Badge></div></div>}
    {tab === 'Expedientes vinculados' && <div className="crm-card"><div className="crm-card-title"><div><h2>Expedientes que utilizan esta ruta</h2><p>Una nueva publicación no modifica automáticamente los casos abiertos.</p></div><Link className="crm-btn" to="/gestion/cambios">Gestionar cambios<Glyph name="arrow" size={16} /></Link></div>{data.expedientes.map(file => <div className="crm-version-row" key={file.id}><span className="crm-square-icon"><Glyph name="cases" /></span><div><h3>{file.nombre}</h3><p>{file.paso} · {file.completados} pasos completados</p></div><Badge>Versión {file.id === 'lucia-demo' && migrated ? 2 : 1}</Badge><Link className="crm-text-btn" to={`/gestion/expedientes/${file.id}`}>Ver expediente →</Link></div>)}</div>}
    {modal === 'preview' && <Modal title="Vista previa del cliente" close={() => setModal(null)}><div className="crm-modal-preview">{preview}</div></Modal>}
    {modal === 'add' && <Modal title="Añadir un paso a la ruta" close={() => setModal(null)}><form onSubmit={e => { e.preventDefault(); if (!newName.trim()) return; const id = `paso-${Date.now()}`; setSteps(s => [...s, { id, titulo: newName.trim(), tipo: 'Seguimiento', instruccion: 'Revisa con el equipo el siguiente paso de tu expediente.', owner: 'Gestor del expediente', required: true, documents: [] }]); setSelected(id); setDirty(true); setReviewed(false); setNewName(''); setModal(null); }}><label className="crm-field">Nombre del nuevo paso<input autoFocus required maxLength={64} value={newName} onChange={e => setNewName(e.target.value)} placeholder="Por ejemplo, consulta de seguimiento" /></label><p className="crm-muted">Se añadirá al final. Después podrás configurar su contenido y posición.</p><div className="crm-modal-actions"><button type="button" className="crm-btn" onClick={() => setModal(null)}>Cancelar</button><button className="crm-btn crm-btn--primary" disabled={!newName.trim()} type="submit">Añadir paso</button></div></form></Modal>}
    {modal === 'publish' && <Modal title="Publicar la versión 2" close={() => setModal(null)}><p>La nueva versión estará disponible para nuevas asignaciones. Los 2 expedientes abiertos conservarán su versión actual.</p><label className="crm-field">Fecha de vigencia<input type="date" value={date} onChange={e => { setDate(e.target.value); setReviewed(false); }} /></label><div className="crm-info"><Glyph name="route" /><span>{steps.length} pasos configurados · {steps.filter(s => s.required).length} revisiones obligatorias</span></div><label className="crm-checkbox"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} />Confirmo la revisión profesional de esta versión de ejemplo.</label><div className="crm-modal-actions"><button className="crm-btn" onClick={() => setModal(null)}>Seguir editando</button><button className="crm-btn crm-btn--primary" disabled={!date || !reviewed || !valid} onClick={() => { setPublished(true); setDirty(false); setModal(null); notify(`Versión 2 publicada en la demo. Vigencia: ${date.split('-').reverse().join('/')}.`); }}>Publicar versión</button></div><p className="crm-modal-note">Publicación simulada, sin cambios en sistemas reales.</p></Modal>}
  </>;
}
